name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231
        with:
          fetch-depth: 0
      - uses: actions/setup-node@0355742c943ddb13ca8a6b700f824231caa91e75
      - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093
        with:
          run_install: true
      - run: pnpm build
      - run: pnpm --filter docs build --base "/${{ github.event.repository.name }}/"
      - uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d
      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9
        with:
          path: ./docs/.vitepress/dist

  deploy:
    runs-on: ubuntu-24.04
    needs: [build]
    permissions:
      pages: write
      id-token: write
    steps:
      - id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
